version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    entrypoint: ["pnpm", "start"]
    ports:
      - "4173:4173"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ["pnpm", "start"]
    ports:
      - "3000:3000"

